### ISSUE TITLE
Merging and compression

### ISSUE THREAD

**Issue by sidnarayanan** [sidnarayanan/PandaAnalysis#43]
It appears that the compression options using in merging (`hadd -ff -n100`) are not optimal. In fact, the defaults seem to perform better. It's not clear why a lower compression level is causing the merging and normalizing to be slower. Need to investigate.

**Comment by DylanHsu** [comment]
Any reason we are not using more aggressive compresson? Only reason to use `hadd -ff` is because changing compression level is expensive, but we are not compressing.

`#include <Compression.h>
TFile::Open(outputFileName,"RECREATE","",ROOT::CompressionSettings(ROOT::kZLIB,9))`

**Comment by sidnarayanan** [comment]
Well, what's the reason for more aggressive compression? If anything, I would argue for less aggressive compression - we're not running out of space and it'll be faster to read. 

That being said, it might be worth making smaller unmerged outputs to make staging out less likely to timeout. But then there's a tradeoff in the merging step.

**Comment by DylanHsu** [comment]
It depends if the bottleneck for processing root files is disk I/O or CPU. Compressing and decompressing the information is orders of magnitude less computationally expensive than e.g. evaluating a BDT or clustering jets, and smaller output files means faster stage out.

**Comment by DylanHsu** [comment]
Of course if we decide to use default compression settings then there is no reason to use `hadd -ff` when `hadd -f` will do

**Comment by sidnarayanan** [comment]
Fixed in #47
