### ISSUE TITLE
CMVA event scale factors are messed up

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#49]
CSVHelper class applies a cut on the discriminator value > 0 which really screws things up for CMVA!

So the event scale factors are wrong. Furthermore, the variations of the weights are taken as the quadrature sum and should be split. We can remove them from the ntuple to make space, and let the user apply them offline in the analysis macro.

I plan to add a short term fix is to add a member function to CSVHelper which gives the per-jet event weight scale factor. Then we can fix the central CMVA weight in PandaAnalysis and drop the CMVA uncertainty branches from GeneralTree.

**Comment by DylanHsu** [comment]
If gen jet reclustering is off, the jet gen flavor is still computed in ModulesBTagSFs, so the CMVA variations are correct online and are stored. but this jet gen flavor is not stored, so individual jet variations cannot be recomputed further down the chain.

**Comment by sidnarayanan** [comment]
I take it this is fixed, modulo #56 ?
