### ISSUE TITLE
PF MET significance inconsistent between GeneralTree and HIG

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#57]
PF met significance distributions have a much smaller mean and variance than the ones pictured in AN for HIG-16-044. This needs to be understood and probably changed.

**Comment by DylanHsu** [comment]
Plotting the puppi met significance in data using the same selection cuts gives a distribution that looks more similar to HIG-16-044. This seems to suggest that the scalar sum ET is only calculated using candidates from the hardest PV.

I will use puppi met significance for the short term. I will submit a PR to fix the issue once it is understood.

maybe useful as a reference:
http://cms.cern.ch/iCMS/jsp/db_notes/noteInfo.jsp?cmsnoteid=CMS%20AN-2013/173

**Comment by DylanHsu** [comment]
Proper algorithm is here
`/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_29/src/RecoMET/METAlgorithms/src/METSignificance.cc`

**Comment by DylanHsu** [comment]
**More information gathering follows**

The configuration for MET significance can be found in the following python files:

1. `/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_29/src/RecoMET/METProducers/python/METSignificance_cfi.py`
2. `/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_29/src/RecoMET/METProducers/python/METSignificanceObjects_cfi.py`
3. `/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_29/src/RecoMET/METProducers/python/METSignificanceParams_cfi.py`

**Notes from python file 1:**
The jets used for the calculation are 15 GeV AK4 PF CHS jets (also from python file 3). I believe in Panda we save the event rho as `event.rho`, is this similar enough to configured setting `srcRho = cms.InputTag('fixedGridRhoAll')` ?

**Notes from python file 2:**
The cuts for the leptons and photons to be used in the MET significance footprint are looser than the standard IDs which means we have to loop over them separately from the existing routines in ModulesLepPho to form the footprint.

**Notes from python file 3:** 
Jet-lepton matching using delta-R < 0.4

**Comment by DylanHsu** [comment]
Conclusion: We do not have enough information to calculate the met significance offline
Next panda production should save it as an event propery (float type).

**Comment by sidnarayanan** [comment]
Can you detail this in an issue for PandaTree then? It's out of the scope of this project. We can put it as a task for a new 009 project.
