### ISSUE TITLE
merge.py creates "events" tree with multiple cycle numbers for large files

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#62]
This leads to problems down the line. Need to use TFile::Delete the older cycle numbers if they exist or write the tree with TObject::kOverwrite

**Comment by sidnarayanan** [comment]
https://github.com/sidnarayanan/PandaCore/commit/c437df30a61a847624be3a109aec0881d1a38fa1

**Comment by sidnarayanan** [comment]
The original problem in this issue has been fixed. If there are still issues with large files, let's isolate that problem and track it in a separate issue.
