### ISSUE TITLE
Huge jet multiplicity causes bug in "hbbjtidx"

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#63]
Noticed a single ttbar event with the following properties which was causing my code to crash:

```
root [13] events->Scan("nJet:nJot:hbbm:hbbjtidx[1]:jetRegFac[1]:jetPt[hbbjtidx[1]]:jetEta[hbbjtidx[1]]:jetPhi[hbbjtidx[1]]","hbbjtidx[1]>nJot","")
    Row   *      nJet *      nJot *      hbbm * hbbjtidx[ * jetRegFac * jetPt[hbb * jetEta[hb * jetPhi[hb *
 13521426 *        18 *        44 * 72.670646 * 1.048e+09 * 0.2261962 *           *           *           *
```

It's easy to protect my code downstream from this rare case by checking the values of hbbjtidx[0], hbbjtidx[1] but I don't understand why this is happening

**Comment by sidnarayanan** [comment]
This is a suspicious event all around...44 jets and 18 central jets?

**Comment by sidnarayanan** [comment]
Is this still an open issue?

**Comment by sidnarayanan** [comment]
Ping
