### ISSUE TITLE
don't use central jets for Hbb reconstruction if they aren't loose id'd jets

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#68]
https://github.com/sidnarayanan/PandaAnalysis/blob/master/Flat/src/ModulesJets.cc#L477 
need to prune non-loosely-identified jets from that collection

**Comment by sidnarayanan** [comment]
Is this still an open issue?

**Comment by sidnarayanan** [comment]
Ping
