### ISSUE TITLE
Btagging 94x

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#83]
update SFs, support DeepCSV

https://twiki.cern.ch/twiki/bin/view/CMS/BtagRecommendation94X

**Comment by sidnarayanan** [comment]
This won't be implemented until we switch over to 010.

**Comment by sidnarayanan** [comment]
(because the DeepCSV tune has changed between releases)

**Comment by sidnarayanan** [comment]
Done
