### ISSUE TITLE
Run python DNN bjet regression

### ISSUE THREAD

**Issue by DylanHsu** [sidnarayanan/PandaAnalysis#84]
https://twiki.cern.ch/twiki/bin/view/Main/BJetRegression
need to:
- compute the energy rings
- save the variables in an auxiliary tree
- convert the aux. tree to numpy
- compute the DNN regression using keras
- add the branch back

**Comment by sidnarayanan** [comment]
Example of how to do this here: https://github.com/sidnarayanan/PandaAnalysis/blob/master/Deep/python/job_deep_utilities.py#L86-L108

**Comment by sidnarayanan** [comment]
Done
